name: Python Linting

on: [push, pull_request]  

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]  
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5  
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
        
    
    - name: Run Python linter (Pylint)
      run: |
        pylint $(git ls-files '*.py') --fail-under=7.0  
        
