name: Python & SQL (MySQL) Linting

on: [push, pull_request]  

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]  
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5  
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sqlfluff
        
    
    - name: Run Pylint (warning mode)
      run: |
        pylint $(git ls-files '*.py') --exit-zero --enable=W 
      continue-on-error: true
      
    - name: Run SQLFluff (MySQL)
      run: |
        sqlfluff lint --dialect mysql $(git ls-files '*.sql')
      continue-on-error: true


        
